version: "3"
services:
    laravel.app:
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: "1000"
        working_dir: /var/www/html
        image: laravel/app:8.1
        container_name: laravel_app
        restart: unless-stopped
        tty: true
        ports:
            - "${APP_PORT:-8000}:80"
        environment:
            WWWUSER: "1000"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
        volumes:
            - ".:/var/www/html"
        networks:
            - laravel

    laravel.node:
        image: node
        container_name: laravel_node
        restart: unless-stopped
        working_dir: /app
        volumes:
            - .:/app
        entrypoint: bash -c "tail -f /dev/null"
        networks:
            - laravel

    laravel.db:
        image: "mariadb:10"
        container_name: laravel_db
        restart: "unless-stopped"
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "laravel_dev"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        networks:
            - laravel
        volumes:
            - "laravel-db:/var/lib/mysql"
            - "./docker/mysql/my.cnf:/etc/mysql/my.cnf"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
            
    laravel.mailhog:
        image: "mailhog/mailhog:latest"
        container_name: laravel_mailhog
        restart: "unless-stopped"
        ports:
            - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025"
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
volumes:
    laravel-db:
        driver: local
